(deftheme ashes-and-ice
  "Created 2016-03-11.")

(custom-theme-set-faces
 'ashes-and-ice
 '(company-echo-common ((t (:foreground "darkgrey"))))
 '(company-preview ((t (:foreground "darkgrey"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "darkgrey" :underline t))))
 '(company-scrollbar-bg ((t (:inherit company-tooltip :background "gray20"))))
 '(company-scrollbar-fg ((t (:background "gray10"))))
 '(company-template-field ((t (:background "gray15" :foreground "sky blue"))))
 '(company-tooltip ((t (:background "gray15" :foreground "sky blue"))))
 '(company-tooltip-common ((t (:inherit company-tooltip :foreground "medium sea green"))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :foreground "medium sea green"))))
 '(company-tooltip-mouse ((t nil)))
 '(company-tooltip-selection ((t (:inherit company-tooltip :background "MediumPurple4"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.728))))
 '(info-title-2 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.44))))
 '(info-title-3 ((((class color) (min-colors 89)) (:family "helv" :weight bold :height 1.2))))
 '(info-title-4 ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(cursor ((t (:background "steel blue"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "gray50"))))
 '(font-lock-comment-face ((t (:foreground "gray50"))))
 '(font-lock-constant-face ((t (:foreground "PaleTurquoise3"))))
 '(font-lock-doc-face ((t (:foreground "dark sea green"))))
 '(font-lock-function-name-face ((t (:foreground "cadet blue"))))
 '(font-lock-keyword-face ((t (:foreground "steel blue"))))
 '(font-lock-preprocessor-face ((t (:foreground "sky blue"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#cfb494"))))
 '(font-lock-type-face ((t (:foreground "plum"))))
 '(font-lock-variable-name-face ((t (:foreground "light steel blue"))))
 '(fringe ((t (:background "gray10"))))
 '(highlight ((((class color) (min-colors 89)) (:background "DodgerBlue4"))))
 '(ido-first-match ((t (:foreground "sandy brown" :weight normal))))
 '(ido-only-match ((t (:foreground "medium spring green"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-keyword-face))))
 '(info-header-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((t (:foreground "SeaGreen2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:family "helv" :weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(info-xref ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(isearch ((((class color) (min-colors 89)) (:background "coral2" :foreground "white"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "cadetblue" :foreground "white"))))
 '(match ((((class color) (min-colors 89)) (:background "DeepPink4"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "gray75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :background nil :foreground "blue4"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "gray40" :foreground "black" :box (:line-width 1 :color "gray40" :style nil)))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(warning ((t (:background "gold"))))
 '(link ((t (:foreground "light steel blue" :underline t))))
 '(linum ((t (:inherit shadow))))
 '(shadow ((t (:foreground "gray40"))))
 '(default ((t (:background "gray7" :foreground "gray70"))))
 '(show-paren-match ((t (:background "sea green"))))
 '(show-paren-mismatch ((t (:background "red" :foreground "white")))))

(provide-theme 'ashes-and-ice)
